config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users
  get 'home/about' => 'homes#show', as: 'about'
  resources :users, only: [:show, :edit, :index, :update]do
    member do
      get :followings, :followers 
    end
  end
  resources :relationships, only: [:create, :destroy]
  
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update, ]do # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    
  end
  resources :groups, only: [ :new, :create, :index, :show, :destroy, :edit, :update,]do
   resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
   get 'search' => 'searches#search'
   
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  attachment :profile_image
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
 
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
 
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def self.search(seach,word)
  if  seach == "forward_match"
    @book = Book.where("title LIKE?","#{word}%") 
    
  elsif seach == "backward_match"
      @book = Book.where("title LIKE?","%#{word}%")
   
  elsif seach == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
          
  elsif seach == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
  else
    @book = Book.all
  end
end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
 belongs_to :user
 belongs_to :book

end

app/models/group.rb
class Group < ApplicationRecord
 has_many :group_users
 has_many:users, through: :group_users
  attachment :profile_image
   attachment :image
   def joined_by?(user)
   group_users.where(user_id: user.id).exists?
   end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
 belongs_to :user
 belongs_to:group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
belongs_to :follower, class_name: "User"
belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy, inverse_of: :follower
  has_many :followings, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy, inverse_of: :followed
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followings, source: :follower
  has_many :group_users
  has_many:groups, through: :group_users
   attachment :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


def follow(user_id)
        followers.create(followed_id: user_id)
end
  
 def following?(user)
    following_users.include?(user)
 end 

def self.search(seach,word)
  if  seach == "forward_match"
    @user = User.where("name LIKE?","#{word}%") 
    
  elsif seach == "backward_match"
      @user = User.where("name LIKE?","%#{word}%")
   
  elsif seach == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
          
  elsif seach == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
  else
    @user = User.all
  end
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:index, :create, :edit, :update, :show,]

  def index
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user.id)
    @users = User.all
  end

  def create
    @book = Book.new(post_book_params)
    @book.user_id = current_user.id
    if @book.save

      redirect_to book_path(@book.id), notice: "Book was successfully created."
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @users = User.find(@books.user_id)
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(post_book_params)
      redirect_to book_path(@book.id), notice: "Book was successfully updated."
    else
      render :edit

    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def post_book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :create, :edit, :update, :show]
  before_action :ensure_current_user, { only: [:edit] }
 
  def ensure_current_user
    if current_user.id != params[:id].to_i

      redirect_to user_path(current_user.id)
    end
  end

  def index
    @user = User.all
    @users = User.find(current_user.id)
    @book = Book.new
    @relationship = @users.followings.find_by(follower_id: current_user.id)
  end

  def show
    @users = User.find(params[:id])
    @books = @users.books.reverse_order
    @book = Book.new
    @relationship = @users.followings.find_by(follower_id: current_user.id)
  end
  def followings
    @user = User.find(params[:id])
    @followings = @user.following_users
  end
    
  def followers
    @user = User.find(params[:id])
    @followers = @user.follower_users
  end
 
 
  def create
    @book = Book.new(post_book_params)
    if @book.user_id = current_user.id
      if @book.save

        redirect_to book_path(@book.id), notice: "Book was successfully created."
      else
        @books = Book.all
        render :index

      end
    else
      render :index
    end
  end

  def edit
    @users = User.find(params[:id])
  end

  def update
    @users = User.find(params[:id])
    if @users.update(user_params)
      redirect_to user_path(@users.id), notice: "User was successfully updated."
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def post_book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/groupusers_helper.rb
module GroupusersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/mail_helper.rb
module MailHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model:[books, book_comment]) do |f| %>
    　<p><%= f.text_area :comment,  size: "80x5" %></p>
  　　<p><%= f.submit "送信" %></p>
<% end %>

app/views/comments/_index.html.erb
　 <% books.book_comments.each do |book_comment| %>
　 <tr>
　  <td>
　   <p> <%= attachment_image_tag book_comment.user, :profile_image,   format: 'image', size: "40x40" , fallback: "no_image.jpg" %><p>
         <%=link_to user_path(book_comment.user) do %>
           <p><%= book_comment.user.name %></p>
          <% end %>
    </td>
    <td><%= book_comment.comment %></td>
        <% if book_comment.user == current_user %>
         <td><%=link_to "Destroy", book_book_comment_path(@books.id),method: :delete,remote: true ,"data-confirm"=>"本当に削除しますか？",class:"btn btn-sm btn-danger "%></td>
        <% end %>
    </tr>    
　 <% end %>
　 

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.post.comments }) %>")
$("textarea").val('')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" media="all" href="/assets/application.scss" data-turbolinks-track="reload">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
  </div>
  </head>

<body>
  <header>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
     <a class="navbar-brand text-light h5" herf="root_path"><span>Bookers</span></a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
       <ul class="navbar-nav ml-auto ">
       <%if user_signed_in?%>
       <li>
        <%= link_to " Home",user_path(current_user.id),class:"fas fa-home nav-link text-light"%>
       </li>  
       <li>
        <%= link_to " Users",users_path,class:"fas fa-users nav-link text-light"%>
       </li>  
       <li>
        <%= link_to " Books",books_path,class:"fas fa-book-open nav-link text-light"%>
       </li>  
       <li>
        <%= link_to " logout",destroy_user_session_path,method: :delete,class:"fas fa-sign-out-alt nav-link text-light "%>
       </li>  
       <% else %>
       <li>
        <%= link_to " Home",root_path,class:"fas fa-home nav-link text-light"%>
       </li>  
    
        <li>
         <%= link_to " About",about_path,class:"fas fa-link nav-link text-light"%>
        </li>  
    
       <li>
        <%= link_to " sign up",new_user_registration_path,class:"fas fa-user-plus nav-link text-light"%>
       </li>  
    
       <li>
        <%= link_to " login",new_user_session_path,class:"fas fa-sign-in-alt nav-link text-light"%>
       </li> 
      <% end %>
      </ul>
    </div>  
   </header>  
   
   <main> 
   <% if user_signed_in? %>
   <div class="container px-5 px-sm-0"> 
    <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-8 offset-md-1">
    
 
      <span><%= form_with url: search_path, method: :get, local: true  do |form| %>
      <%= form.text_field :word %>
       <%= form.submit "検索" %>
　　  <%=  form.select :range ,[['---選択してください---', ''], ['User', '1'], ['Book', '2']] %>
      <%=  form.select :search, [["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]] %>
   </div>
   </div>
   </div>
   <% end %>

<% end %>

     <%flash.each do |message_type, message|%>
     <p id="notice"><%= message%></p>
     <% end %>
    <%= yield %>
   </main>
   <footer>
    <div class="container mt-5">
      <div class="row">
       <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
       </div>
     </div>    
        
    </div>
   </footer>
  </body>
</html>