config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users
  get 'home/about' => 'homes#show', as: 'about'
  resources :users, only: [:show, :edit, :index, :update]do
    member do
      get :followings, :followers 
    end
  end
  resources :relationships, only: [:create, :destroy]
  
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update, ]do # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    
  end
  resources :groups, only: [ :new, :create, :index, :show, :destroy, :edit, :update,]do
   resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
   get 'search' => 'searches#search'
   
end 

app/models/group.rb
class Group < ApplicationRecord
 has_many :group_users
 has_many:users, through: :group_users
  attachment :profile_image
   attachment :image
   def joined_by?(user)
   group_users.where(user_id: user.id).exists?
   end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
 def new
   @group = Group.new

 end

  def create
    @group = Group.new(post_group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    @group.save
     redirect_to groups_path
  end

 def index
   @groups = Group.all
   @book = Book.new
   @user = User.find(current_user.id)
   @users = User.all
 end
  
 def  show
    @book = Book.new
    @group = Group.find(params[:id])
    @user = User.find(current_user.id)
   @group_users = GroupUser.where(group_id: @group.id)

  
 end
 
  def edit
     @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end

  def update
    @group = Group.find(params[:id])
    @group.update(post_book_params)

  end
  
  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @title = params[:title]
    @content = params[:content]
    GroupMailer.send_mail(group_users, @title, @content).deliver
  end
  private

  
 def post_group_params
    params.require(:group).permit(:name, :image, :introduction)
 end
 
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
 <div class="container">
   

   <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h2>Editing Group</h2>
       
        
        
        <%= form_with model: @group,  local:true do |f| %>
         　<div class="form-group">
               <label for="group_name">グループ名</label>
                  <%= f.text_field :name,class:" form-control name" %>
           </div>


            <div class="form-group">
              <label for="group">紹介文</label>
              <%= f.text_area :introduction,class:" form-control introduction" %>
             </div>
              
          　<div class="group_immage">
               <label for="user">グループ画像</label>
              <p> <%= f.attachment_field :image %></p>
            </div>
              
             <%= f.submit 'Update group',class:"btn btn-info" %>
       <% end %>
      </div> 
     </div>  
    </div>  

app/views/groups/index.html.erb
<div class="container px-5 px-sm-0"> 



<div class="row">
 
  <%= render'books/book',book:@book ,users:@user%>
 
<div class="col-md-8 offset-md-1">
 <h2>Groups</h2>

<table class="table"> 
 <thead>
  <tr>
   <th></th>
   <th>グループ名</th>
   <th>紹介文</th>
   <th>メンバー数</th>
   <th></th>
  </tr> 
  </thead>
  <tbody>
 
  <%  @groups.each do |group| %> 
     <tr>
     <td>
      <%= attachment_image_tag group,:image, format: 'image', size: "40x40" , format: 'jpeg', fallback: "no_image.jpg" %>
    </td>
     <td>
      <%=link_to group_path(group.id) do%> <%=group.name%><% end %>
      </td>
     <td><%= group.introduction%></td>
      <td><%= group.users.count %></td>
     <% if group.owner_id == current_user.id %>
     <td><%=link_to "Edit",edit_group_path(group.id),class:"btn btn-sm btn-success "%></td>
    <%end %>
    </tr>
   <% end %>
  
   </tbody>
   </table>
  </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
   

   <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h2>Create Group</h2>
       
        
        
        <%= form_with model: @group,  local:true do |f| %>
         　<div class="form-group">
               <label for="user_name">グループ名</label>
                  <%= f.text_field :name,class:" form-control name" %>
           </div>


            <div class="form-group">
              <label for="user">Introduction</label>
              <%= f.text_area :introduction,class:" form-control introduction" %>
             </div>
            <div class="form-group">
              
          　　 <div class="user-image">
               <label for="user">Image</label>
               <%= f.attachment_field :image %>
            　</div>
              
             <%= f.submit 'Create group',class:"btn btn-secondary" %>
       <% end %>
      </div> 
     </div>  
    </div>  

app/views/groups/new_mail.html.erb
<div class="container">
   

   <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h2>Event Mail</h2>
       
        
        
        <%= form_with url: group_send_mail_path(@group), method: :get, local:true do |f| %>
         　<div class="form-group">
               <label for="group_name">Title</label>
                  <%= f.text_field :title,class:" form-control title" %>
           </div>


            <div class="form-group">
              <label for="group">Content</label>
              <%= f.text_area :content,class:" form-control content" %>
             </div>
           
          　
              
            <%= f.submit '送信',class:"btn btn-info" %>
       <% end %>
     
      </div> 
     </div>  
    </div>  

app/views/groups/send_mail.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h3 class="margin_top text-center">送信が完了しました</h3>
   <div class="main_width">
   <div class="margin_top">内容は以下の通りです。</div>
    <div class="small_margin_top">
      [タイトル]<p class="font-weight-bold"> <%= @title %></p>
    </div>
    <div>
      [本文]<p class="font-weight-bold"> <%= safe_join(@content.split("\n"),tag(:br)) %></p>
    </div>
   </div>
   </div>
  </div>
 </div>
</div>

app/views/groups/show.html.erb
<div class="container px-5 px-sm-0"> 
<div class="row">
 
 
 <%= render'books/book',book:@book ,users:@user %>
 
 
 <div class="col-md-8 offset-md-1">
 <h2>Group Detail</h2>
<table class="table table-hover table-inverse"> 
 
  <tbody>
    <tr>
   <th></th>
   <th>グループ名</th>
   <th>紹介文</th>
   <th >メンバー</th>
   <th></th>
  </tr> 
    <tr>
     <td>
      <%= attachment_image_tag @group,:image, format: 'image', size: "40x40" , format: 'jpeg', fallback: "no_image.jpg" %>
    </td>
    
     <td> <%=@group.name%></td>
     <td><%= @group.introduction%></td>
      
      <td>
      <%@group.users.each do |member|%>
      <%= member.name %><br>
      <% end %>
     </td>
    
     <% if @group.owner_id == current_user.id %>
     <td><%=link_to "Edit",edit_group_path(@group.id),class:"btn btn-sm btn-success "%></td>
     <td><%=link_to "Notice an Event",group_new_mail_path(@group),class:"btn btn-sm btn-info "%></td>
     <% else %>
       <% if @group.joined_by?(current_user) %>
        
         <td> <%= link_to" Leave this group",  group_group_users_path(@group.id), method: :delete,class:"btn btn-sm btn-danger" %></td>
         <% else %>
           <td><%= link_to "Join this group", group_group_users_path(@group.id), method: :post, class:"btn btn-sm btn-success " %></td>
           
           <% end %>
            
        
    <% end %>
    
    </tr>
  
  
    </tbody>
   </table>