config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users
  get 'home/about' => 'homes#show', as: 'about'
  resources :users, only: [:show, :edit, :index, :update]do
    member do
      get :followings, :followers 
    end
  end
  resources :relationships, only: [:create, :destroy]
  
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update, ]do # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    
  end
  resources :groups, only: [ :new, :create, :index, :show, :destroy, :edit, :update,]do
   resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
   get 'search' => 'searches#search'
   
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy, inverse_of: :follower
  has_many :followings, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy, inverse_of: :followed
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followings, source: :follower
  has_many :group_users
  has_many:groups, through: :group_users
   attachment :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


def follow(user_id)
        followers.create(followed_id: user_id)
end
  
 def following?(user)
    following_users.include?(user)
 end 

def self.search(seach,word)
  if  seach == "forward_match"
    @user = User.where("name LIKE?","#{word}%") 
    
  elsif seach == "backward_match"
      @user = User.where("name LIKE?","%#{word}%")
   
  elsif seach == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
          
  elsif seach == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
  else
    @user = User.all
  end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :create, :edit, :update, :show]
  before_action :ensure_current_user, { only: [:edit] }
 
  def ensure_current_user
    if current_user.id != params[:id].to_i

      redirect_to user_path(current_user.id)
    end
  end

  def index
    @user = User.all
    @users = User.find(current_user.id)
    @book = Book.new
    @relationship = @users.followings.find_by(follower_id: current_user.id)
  end

  def show
    @users = User.find(params[:id])
    @books = @users.books.reverse_order
    @book = Book.new
    @relationship = @users.followings.find_by(follower_id: current_user.id)
  end
  def followings
    @user = User.find(params[:id])
    @followings = @user.following_users
  end
    
  def followers
    @user = User.find(params[:id])
    @followers = @user.follower_users
  end
 
 
  def create
    @book = Book.new(post_book_params)
    if @book.user_id = current_user.id
      if @book.save

        redirect_to book_path(@book.id), notice: "Book was successfully created."
      else
        @books = Book.all
        render :index

      end
    else
      render :index
    end
  end

  def edit
    @users = User.find(params[:id])
  end

  def update
    @users = User.find(params[:id])
    if @users.update(user_params)
      redirect_to user_path(@users.id), notice: "User was successfully updated."
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def post_book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
 <div class="container">
   

   <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h2>User info</h2>
        <% if @users.errors.any? %>

        <div id="error_explamation">
        <h2><%= @users.errors.count %>error prohibited this book from being saved:</h2>
        <ul>
        <% @users.errors.full_messages.each do |message| %>
        <li><%= message %></li>
          <%end%>
        </ul>
        </div>

        <% end %>

        
        
        
        <%= form_with model: @users,  local:true do |f| %>
         <div class="form-group">
               <label for="user_name">Name</label>
                  <%= f.text_field :name,class:" form-control name" %>
           </div>

           <div class="user-image">
               <label for="user">Image</label>
               <%= f.attachment_field :profile_image %>
            </div>

            <div class="form-group">
              <label for="user">Introduction</label>
              <%= f.text_area :introduction,class:" form-control introduction" %>
             </div>
            <div class="form-group">
             <%= f.submit 'Update User',class:"btn btn-secondary" %>
       <% end %>
      </div> 
     </div>  
    </div>  

app/views/users/followers.html.erb
<h2>Follower Users </h2>
<% if @followers.exists? %>
 
  <table class="table table-striped">
   <thead>  
    <tr>
      <th>image</th>
      <th>name</th>
      <td>   </td>
      <td></td>
    </tr>
  </thead>
  <tbody>
 
   <% @followers.each do |user| %>
    <tr>
     <td>
      <%= attachment_image_tag user,:profile_image, format: 'image', size: "40x40" , format: 'jpeg', fallback: "no_image.jpg" %>
    
     </td>
     <td><%=user.name%></td>
     <td>フォロー数:<%=user.followings.count %></td>
     <td>フォロワー数:<%=user.followers.count %></td>
     <td><%=link_to "Show",user_path(user.id)%></td>
    </tr> 
    <%end%>
   
  <%else%> 
   <p>ユーザーはいません</p>
  <%end%>
   </tbody>

  
  </table>

app/views/users/followings.html.erb
<h2>Follow Users </h2>
 <% if @followings.exists? %>
  <table class="table table-striped">
   <thead>  
    <tr>
      <th>image</th>
      <th>name</th>
      
    </tr>
  </thead>
  <tbody>
　
  
   <% @followings.each do |user| %>
    <tr>
     <td>
      <%= attachment_image_tag user,:profile_image, format: 'image', size: "40x40" , format: 'jpeg', fallback: "no_image.jpg" %>
    
     </td>
     <td><%=user.name%></td>
     <td>フォロー数:<%=user.followers.count %></td>
     <td>フォロワー数:<%=user.followingss.count %></td>
     <td><%=link_to "Show",user_path(user.id)%></td>
    </tr> 
    <%end%>
  <%else%> 
   <p>ユーザーはいません</p>
  <%end%>
   </tbody>

  
  </table>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0"> 



<div class="row">
 
  <%= render'books/book',book:@book ,users:@users%>
 
<div class="col-md-8 offset-md-1">
 <h2>Users</h2>
<%= link_to "グループを作成する",new_group_path %>|<%= link_to "グループ一覧",groups_path %>
<table class="table"> 
 <thead>
  <tr>
   <th></th>
   <th>image</th>
   <th>name</th>
   <th colspan="3"></th>
  </tr> 
  </thead>
  <tbody>
  <%  @user.each do |user| %> 
   <tr>
     <td>
      <%= attachment_image_tag user,:profile_image, format: 'image', size: "40x40" , format: 'jpeg', fallback: "no_image.jpg" %>
    
     </td>
     <td><%=user.name%></td>
     <td>フォロー数:<%=user.followers.count %></td>
     <td>フォロワー数:<%=user.followings.count %></td>
     <% unless user == current_user %>
      <% if current_user.following?(user) %>
     
      <td><%= link_to "フォローを外す",relationship_path(@users),method: :delete%></td>
     
     <% else %>
     
       
      <td><%= link_to "フォローをする",relationships_path(:follow_id => user.id ),method: :post %></td>
      
      <% end %> 
    <% end %>
     <td><%=link_to "Show",user_path(user.id)%></td>
    </tr> 
  <%end%>
   </tbody>
   </table>
  </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0"> 
 <div class="row">
 
 <%= render'books/book',book:@book ,users:@users%>
 
 <div class="col-md-8 offset-md-1">
 <h2>Books</h2>
<table class="table table-hover table-inverse"> 
 <thead>
  <tr>
   <th></th>
   <th>Title</th>
   <th>Opinion</th>
   <th colspan="3"></th>
  </tr> 
  </thead>
  <tbody>
  <% @books.each do |book| %>
   <tr>
     <td>
      <%=link_to user_path(book.user_id) do %>
      <%= attachment_image_tag @users, :profile_image,  format: 'image', size: "40x40" , fallback: "no_image.jpg" %>
      <% end %>
     </td>
     <td><%=link_to book_path(book.id) do %><%=book.title%><% end %></td>
     <td><%=book.body%></td>
     <td>コメント件数：<%= book.book_comments.count %></td>
    </tr> 
   <% end %> 
   </tbody>
   </table>
  </div>
  </div>
  </div>