config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users
  get 'home/about' => 'homes#show', as: 'about'
  resources :users, only: [:show, :edit, :index, :update]do
    member do
      get :followings, :followers 
    end
  end
  resources :relationships, only: [:create, :destroy]
  
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update, ]do # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    
  end
  resources :groups, only: [ :new, :create, :index, :show, :destroy, :edit, :update,]do
   resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
   get 'search' => 'searches#search'
   
end 

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
 
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
 
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def self.search(seach,word)
  if  seach == "forward_match"
    @book = Book.where("title LIKE?","#{word}%") 
    
  elsif seach == "backward_match"
      @book = Book.where("title LIKE?","%#{word}%")
   
  elsif seach == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
          
  elsif seach == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
  else
    @book = Book.all
  end
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:index, :create, :edit, :update, :show,]

  def index
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user.id)
    @users = User.all
  end

  def create
    @book = Book.new(post_book_params)
    @book.user_id = current_user.id
    if @book.save

      redirect_to book_path(@book.id), notice: "Book was successfully created."
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @users = User.find(@books.user_id)
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(post_book_params)
      redirect_to book_path(@book.id), notice: "Book was successfully updated."
    else
      render :edit

    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def post_book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="col-md-3">
     <h2>User info</h2>
      
 <%= attachment_image_tag users, :profile_image,  format: 'image', size: "100x100" , fallback: "no_image.jpg" %>

        <table class="table">
          <tbody>
            <tr></tr>
             <tr>
             <th>name</th>
              <th><%= users.name%></th>
             
             </tr> 
            
            <tr>
              <th>introduction</th>
              <th><%= users.introduction%></th>
              
            </tr>
            <tr>
              <th>follows</th>
              <th><%= link_to " #{users.followers.count}", followings_user_path(users.id) %></th>
            </tr>  
             <tr>
              <th>followers</th>
              <th><%= link_to " #{users.followings.count}", followers_user_path(users.id) %></th>
             </tr>  
     
      <% unless users == current_user %>
        <%if current_user.following?(users)%>
         
       <tr>
         <th> <%=link_to "フォローを外す",relationship_path(users),method: :delete,class:"btn btn-sm btn-info"%></th>
        
        <% else %>
         
          
          <th><%= link_to "フォローをする",relationships_path(:follow_id => @users.id ),method: :post, class:"btn btn-sm btn-success"%></th>
         
        <% end %> 
      <% end %>
      </tr>
      </table> 
  <div class="row">
      <%=link_to "",edit_user_path(users.id),class:"btn btn-outline-secondary btn-block fas fa-user-cog"%> 
    
  </div>

  
  <h2 class="mt-3">New book</h2>

 <%= form_with model: book,  local:true do |f| %>

 
 
 <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title,class:" form-control book_title" %>
  </div>

  <div class="form-group">
     <label for="book_opiniony">Opinion</label>
     <%= f.text_area :body,class:"form-control book_body" %>
  </div>

  <div class="form-group">
   <%= f.submit 'Create Book',class:"btn btn-success" %>
  </div>
<% end %>
 </div>
 

app/views/books/edit.html.erb
 <div class="container">
   <% if @book.errors.any? %>

   <div id="error_explamation">
   <h2><%= @book.errors.count %>error prohibited this book from being saved:</h2>
   <ul>
    <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
       <%end%>
   </ul>
   </div>

  <% end %>


   <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h1>Editing Book</h1>
        <%= form_with model: @book,  local:true do |f| %>
           <div class="form-group">
               <label for="book_title">Title</label>
                  <%= f.text_field :title,class:" form-control book_title" %>
           </div>

           <div class="form-group">
               <label for="book_opiniony">Opinion</label>
                 <%= f.text_area :body,class:"form-control book_body" %>
            </div>

            <div class="form-group">
               <%= f.submit 'Update Book',class:"btn btn-success" %>
            </div>
             <% end %>
               <%= link_to "Show",book_path(@book.id)%>|<%= link_to "Back",books_path%>
      </div>
    </div>
  </div>  

app/views/books/index.html.erb
<div class="container px-5 px-sm-0"> 
 <% if @book.errors.any? %>

   <div id="error_explamation">
   <h2><%= @book.errors.count %>error prohibited this book from being saved:</h2>
   <ul>
    <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
       <%end%>
   </ul>
   </div>

  <% end %>


<div class="row">
 <div class="col-md-3">
     <h2>User info</h2>
      
 <%= attachment_image_tag @user, :profile_image,  format: 'image', size: "100x100" , fallback: "no_image.jpg" %>

        <table class="table">
          <tbody>
            <tr></tr>
             <tr>
             <th>name</th>
              <th><%= current_user.name%> </th>
             
             </tr> 
            
            <tr>
              <th>introduction</th>
              <th><%= current_user.introduction%></th>
              
            </tr>
        </table>
        
  
  <div class="row">
      <%=link_to "",edit_user_path(current_user.id),class:"btn btn-outline-secondary btn-block fas fa-user-cog"%> 
    
  </div>
  <h2 class="mt-3">New book</h2>

 <%= form_with model: @book,  local:true do |f| %>

 
 
 <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title,class:" form-control book_title" %>
  </div>

  <div class="form-group">
     <label for="book_opiniony">Opinion</label>
     <%= f.text_area :body,class:"form-control book_body" %>
  </div>

  <div class="form-group">
   <%= f.submit 'Create Book',class:"btn btn-success" %>
  </div>
<% end %>
 </div>
 

 <div class="col-md-8 offset-md-1">
 <h2>Books</h2>
<table class="table table-hover table-inverse"> 
 <thead>
  <tr>
   <th></th>
   <th>Title</th>
   <th>Opinion</th>
   <th colspan="3"></th>
  </tr> 
  </thead>
  <tbody>
  <% @books.each do |book| %> 
   <tr>
     <td><%=link_to user_path(book.id) do %>
      <%= attachment_image_tag book.user, :profile_image,   format: 'image', size: "40x40" , fallback: "no_image.jpg" %>
     <% end %>
     </td>
     <td><%=link_to book_path(book.id) do%><%=book.title%><% end %></td>
     <td><%=book.body %></td>
    
     
     　<td>
     
        <%= render 'favorites/favorite-btn',  book:book %>
      　
      </td>
     
  　 <td>
       コメント件数：<%= book.book_comments.count %>
    </td>    
    </tr> 
   <% end %> 
   </tbody>
   </table>
  </div>
  </div>
  </div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0"> 
<div class="row">
 
 
 <%= render'books/book',book:@book ,users:@users, relationship:@relationship%>
 
 
 <div class="col-md-8 offset-md-1">
 <h2>Book detail</h2>
<table class="table table-hover table-inverse"> 
 
  <tbody>
    
   <tr>
     <td><%=link_to user_path(@books.user.id) do %>
      <%= attachment_image_tag @users, :profile_image, format: 'image', size: "40x40", fallback: "no_image.jpg" %><br>
     <%= @books.user.name %>
     <% end %>
     </td>
     <td><%=link_to books_path do %><%=@books.title%><% end %></td>
     <td><%=@books.body %></td>
    
     　
     <td>
       <%= render 'favorites/favorite-btn',  book:@books %>
      　
    </td>
   
    <td>
      コメント数：<%= @books.book_comments.count %>
    </td>    
  
     <% if @books.user == current_user %>
     <td><%=link_to "Edit",edit_book_path(@books.id),class:"btn btn-sm btn-success "%></td>
     <td><%=link_to "Destroy",book_path(@books.id),method: :delete,"data-confirm"=>"本当に削除しますか？",class:"btn btn-sm btn-danger "%></td>
   
    <% end %>
    </tr> 
   
   </tbody>
   </table>
    <table>
　　　<tbody id="comments_area">
　　　  <%= render partial: 'comments/index', locals: { books: @books } %>
　　　</tbody>
　　</table> 
　   <div id="new-comment">
       <%= render partial: 'comments/form', locals: { books: @books, book_comment: @book_comment } %>
     </div> 　
  　
  
  </div>
  </div>

 